export const FETCH_GAMES = "FETCH_GAMES";
export const FILTER_GAMES_BY_GENRE = "FILTER_GAMES_BY_GENRE";
export const ORDER_PRODUCTS_BY_PRICE = "ORDER_PRODUCTS_BY_PRICE";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const PLACE_PRODUCT_AT_END_OF_LIST = "PLACE_PRODUCT_AT_END_OF_LIST";